In [6]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import os
import cv2
from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix, accuracy_score

In [7]:
diseases=["Atelectasis",
"Consolidation",
"Infiltration",
"Pneumothorax",
"Edema",
"Emphysema",
"Fibrosis",
"Effusion",
"Pneumonia",
"Pleural_thickening",
"Cardiomegaly",
"Nodule","Mass",
"Hernia"]

In [9]:
data_path="D:/Projects/Major Project/data/newdata/"
for i in range(14):
    x=np.load(data_path+str(i)+"/x.npy")
    y=np.load(data_path+str(i)+"/y.npy")
    perm=np.random.permutation(len(y))
    x=x[perm]
    y=y[perm]
    x_test,y_test=x[:6000],y[:6000]
    model = keras.models.load_model("Website/models/"+str(i)+"/"+str(i)+".h5")
    y_pred=model.predict(x_test)
    y_pred=np.array([0 if i<0.5 else 1 for i in y_pred])
    
    print("--------Metrics of the Model that predicts the disease "+diseases[i]+" are--------")
    print("Precision Score is ",precision_score(y_test, y_pred ))
    print("Recall Score is ",recall_score(y_test, y_pred ))
    print("F1 score is ", f1_score(y_test, y_pred ))
    print("Accuracy score is ",accuracy_score(y_test,y_pred))
    print("Confusion Matrix is \n",confusion_matrix(y_test,y_pred))
    print("----------------------------")
    

--------Metrics of the Model that predicts the disease Atelectasis are--------
Precision Score is  0.794088989931796
Recall Score is  0.8339017735334243
F1 score is  0.8135085676260189
Accuracy score is  0.8131666666666667
Confusion Matrix is 
 [[2434  634]
 [ 487 2445]]
----------------------------
--------Metrics of the Model that predicts the disease Consolidation are--------
Precision Score is  0.9017080244924267
Recall Score is  0.9137818419333769
F1 score is  0.907704785077048
Accuracy score is  0.9051666666666667
Confusion Matrix is 
 [[2633  305]
 [ 264 2798]]
----------------------------
--------Metrics of the Model that predicts the disease Infiltration are--------
Precision Score is  0.9146999325691166
Recall Score is  0.8886341303635769
F1 score is  0.9014786509386942
Accuracy score is  0.9011666666666667
Confusion Matrix is 
 [[2694  253]
 [ 340 2713]]
----------------------------
--------Metrics of the Model that predicts the disease Pneumothorax are--------
Precision Sco